### PR TITLE
Development branch

### PR DESCRIPTION
**Pull request by rsundar**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Nice job @rsundar 👍
Your project's almost ready, we just need to make some changes to be in line with Microverse guidelines. The changes are:

- [x] All content should be wrapped with `main` HTML tags
- [x] Every child of main should be a `section` HTML tag pair
- [x] Every child of section should be an `article` HTML tag pair

- [x] Each one of the 4 50% width articles (div class="articles") should have an image in the top left corner with the title of an article under it. The 4 articles must be inside a section tag, and each one must be inside an article tag. The 4 articles need to have a placeholder text.

- [x] The 3 articles of 33% width ( second-article-row) are missing the placeholder text. Also, change this container for a section tag (all sections in this page must be a section tag), and use the article tag for each one of the three articles( all articles in this page should be inside an article tag)

- [x] Your footer lacks the link's list. The links in the footer should cover the central part of the footer, both horizontally and vertically

- [x] There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/). Ignore the warnings.

Please, make these changes and submit for code review again.

**Comment by rsundar** [comment]
Could you please explain why I would need to wrap every section in a section and every article in an article tag? I would need to make a lot of changes to my css to keep every thing in place. I would like a proper explanation for why this needs to be done, and if they are microverse guidelines why were they  not mentioned in the required readings or project descriptions? 

None of these changes would either change the outcome of the project (you can approach a project in many different ways in css and html) which can viewed in the live preview or illustrate any design principles. Why not use divs instead of sections? If the outcome of this project is to just check the mentioned checkboxes could you please highlight which design principles were at play here? 

Thanks,

Rohan

**Comment by Torres-ssf** [comment]
Hi there @rsundar. I'm really sorry about that. I know how changing things can be annoying. I asked you to make these changes because they are Microverse guidelines for this project. The principle behind this it's about semantic. Div containers have no semantic value at all. HTML5 introduces many new semantic tags that improve the value of your code, and it's best practice to use them. Make your code semantic its important for many reasons. Screen readers, for example, don't just read the site content, they also use HTML tags to understand and describe it, thus the person with accessibility has a better understanding on how the site is structured and what is the content of the section they currently are. Semantic tags make it clear to the browser what the meaning of a page and its content is. That clarity is also communicated with search engines, ensuring that the right pages are delivered for the right queries.
I know this project is very simple but I think Microverse created these guidelines to make students use the best practices.

**Comment by maelfosso** [comment]
Hello @rsundar 

Really, you did a really good job.
But, please, to the reasons @Torres-ssf  told you, I could add that there are some of the international standards in coding that Microverse wants their students to get.
So please, let just follow them. Making those changes may give you more pieces of knowledge.

Thanks

**Pull request merged**
